name: test
on:
  # push trigger required to get coveralls monitoring of default branch
  # pull_request required to get PR comments
  pull_request:
    paths-ignore:
      ['**/*md', '**/*yaml', '!.github/workflows/test.yaml', '**/*yml']
  push:
    branches: [main]
    paths-ignore: ['**/*md', '**/*yaml', '**/*yml']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun test --coverage --coverage-reporter lcov --coverage-dir .
      - name: Coveralls
        uses: coverallsapp/github-action@v2.3.0
        with:
          format: lcov
          file: lcov.info
