name: Test Coverage
on:
  # push trigger required to get coveralls monitoring of default branch
  # pull_request required to get PR comments
  pull_request:
    paths-ignore: ['**/*md', '**/*yaml', '**/*yml']
  push:
    branches: [main]
    paths-ignore: ['**/*md', '**/*yaml', '**/*yml']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          node-version: 19

      - name: Setup turbo cache
        id: turbo-cache
        uses: actions/cache@v3
        with:
          path: .turbo
          key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: turbo-${{ github.job }}-${{ github.ref_name }}-

      - name: Install
        run: bun install

      - name: Test
        run: bun run test
# no supported by bun test yet
#      - name: Coveralls
#        uses: coverallsapp/github-action@master
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          path-to-lcov: ./coverage/lcov.info
